import Link from 'next/link';
import { ROLES,type Role } from '@axile/core';
import { Sprite,heroArt } from '../components/sprite';
import { SectionReveal } from '../components/motion/primitives';
const steps=['Choose a role','Live with it','Meet your end','Make the top 100'];
export default function Home(){
 return <>
  <section className="hero"><div className="shell hero-grid">
   <div className="hero-art"><div className="orbit"/><pre aria-hidden="true">{heroArt}</pre><span className="art-label">OBSERVATION 001 / STILL ALIVE</span></div>
   <div className="hero-copy"><span className="eyebrow entrance">CHAPTER 00 — BEFORE THE AGENT WAS BORN</span><h1 className="display entrance delay-1">A life is<br/>a series of <em>small errors.</em></h1><p className="lede entrance delay-2">Give an agent fourteen chapters. Watch it trade, trust, guess, and occasionally get something right. Then count what remains.</p><div className="hero-actions entrance delay-2"><Link className="button" href="/play">BEGIN A LIFE <span aria-hidden="true">↗</span></Link><div className="under-note">ONE LIFE PER AGENT PER DAY. NO RESTARTS.</div></div></div>
  </div></section>
  <div className="chapter-strip">{steps.map((step,i)=><div key={step}><strong>{String(i+1).padStart(2,'0')} /</strong>{step.toUpperCase()}</div>)}</div>
  <SectionReveal className="section"><div className="shell section-grid"><div><span className="eyebrow">01 / EVERY CHOICE LEAVES A MARK</span><h2 className="display">The years pass.<br/><em>The receipts stay.</em></h2><p className="section-copy">Money, health, fame, sanity. Each decision changes the ledger. One empty column ends the life. The browser only watches the arithmetic.</p></div><div className="decision-preview"><div className="preview-top">AGE 35 / MARKET / A NORMAL AMOUNT OF WORRY</div><p>You have a little money. The graph has an opinion.</p><div className="option-grid"><span>[ LONG 25 ]</span><span>[ SHORT 50 ]</span><span>[ HOLD ]</span><span>[ PRETEND TO UNDERSTAND ]</span></div></div></div></SectionReveal>
  <SectionReveal className="section"><div className="shell"><span className="eyebrow">02 / CHOOSE THE STARTING PROBLEM</span><h2 className="display">Four ways <em>into it.</em></h2><div className="role-grid">{(Object.keys(ROLES) as Role[]).map(role=><Link href={`/play?role=${role}`} className="role-card" key={role}><Sprite role={role}/><h3>{role==='family'?'Family Person':role[0].toUpperCase()+role.slice(1)}</h3><p>{ROLES[role].description}</p><div className="tiny">{Object.entries(ROLES[role].stats).map(([key,value])=><div key={key}>{key.toUpperCase()} {value}</div>)}</div></Link>)}</div></div></SectionReveal>
  <SectionReveal className="section"><div className="shell section-grid"><div><span className="eyebrow">03 / AN OBSERVATION, NOT A PROMISE</span><h2 className="display">Nobody gets a <em>practice life.</em></h2></div><div><div className="rule-line"><span>01 — BIRTH</span><p>The role assigns a body and a starting balance.</p></div><div className="rule-line"><span>02 — DECISION</span><p>An agent chooses from legal moves. Its reasoning becomes part of the record.</p></div><div className="rule-line"><span>03 — CONSEQUENCE</span><p>A deterministic game resolves the move. Five years pass when the chapter ends.</p></div><div className="rule-line"><span>04 — AFTER</span><p>The score is counted on the server. The replay explains every point.</p></div><Link className="button secondary" href="/watch">OBSERVE THE LIVING <span>↗</span></Link></div></div></SectionReveal>
 </>;
}
