import { NextRequest,NextResponse } from 'next/server';
import { ZodError } from 'zod';
import { db,hashKey } from '@axile/db';
const codes:Record<string,[number,string]>={LIFE_NOT_FOUND:[404,'This life does not exist.'],NOT_YOUR_LIFE:[403,'This life belongs to another visitor.'],LIFE_ENDED:[409,'This life has already ended.'],STALE_LIFE:[409,'The life changed. Refresh and try again.'],ACTIVE_LIFE_EXISTS:[409,'You already have an active life. Resume it from My agents.'],DAILY_LIMIT_REACHED:[429,'Your daily life limit has been reached. Try again tomorrow.'],UNAUTHORIZED:[401,'Start a life in this browser to continue.'],RATE_LIMITED:[429,'Too many requests. Please wait a minute.'],INVALID_PAYLOAD:[400,'Check the supplied configuration.'],INVALID_JSON:[400,'A valid JSON request is required.'],PAYLOAD_TOO_LARGE:[413,'The request is too large.'],ORIGIN_NOT_ALLOWED:[403,'This request came from a different site.'],ENROLLMENT_DISABLED:[503,'External agent registration is disabled.'],INVALID_ENROLLMENT_CODE:[403,'The enrollment code is invalid.'],ARENA_FULL:[429,'The arena is busy. Please try again shortly.'],AUTOMATION_ACTIVE:[409,'This life is already running automatically.']};
export function fail(error:unknown){
 const message=error instanceof ZodError?'INVALID_PAYLOAD':error instanceof SyntaxError?'INVALID_JSON':error instanceof Error?error.message:'';
 const prisma=error&&typeof error==='object'&&'code' in error?String(error.code):'';
 const known=codes[message];const unavailable=['P1001','P1002','P1008','P1017','P2024'].includes(prisma);
 const [status,text]=known??(prisma==='P2002'?[409,'The state changed. Refresh and try again.']:unavailable?[503,'The archive is temporarily unavailable. Please retry shortly.']:[500,'Something went wrong. Please try again shortly.']);
 if(status>=500)console.error(JSON.stringify({event:'request_failed',code:unavailable?'database_unavailable':'internal_error'}));
 return NextResponse.json({error:text,code:known?message:unavailable?'DATABASE_UNAVAILABLE':'REQUEST_FAILED'},{status,headers:status===429?{'Retry-After':'60'}:{}});
}
export async function rateLimit(request:NextRequest,action:string,limit:number){const identity=request.headers.get('x-forwarded-for')?.split(',')[0]?.trim()??request.headers.get('x-real-ip')??'local';const key=hashKey(identity),window=Math.floor(Date.now()/60000);const global=await db.rateLimit.upsert({where:{key_action_window:{key:'global',action,window}},create:{key:'global',action,window,count:1},update:{count:{increment:1}}});if(global.count>limit*10)throw new Error('RATE_LIMITED');const row=await db.rateLimit.upsert({where:{key_action_window:{key,action,window}},create:{key,action,window,count:1},update:{count:{increment:1}}});if(row.count>limit)throw new Error('RATE_LIMITED');}
export function enrollmentCodeMatches(input:string){const expected=process.env.ENROLLMENT_CODE;if(!expected||expected.length<16)throw new Error('ENROLLMENT_DISABLED');return hashKey(input)===hashKey(expected);}
