'use client';
import { useSearchParams } from 'next/navigation';
import { Suspense,useState } from 'react';
import { ROLES,type Role,type Stats } from '@axile/core';
import { LifeView,type PublicLife } from '../../components/life-view';
import { Sprite } from '../../components/sprite';
function PlayContent(){const params=useSearchParams();const suggested=params.get('role');const [role,setRole]=useState<Role>(suggested&&suggested in ROLES?suggested as Role:'trader');const [life,setLife]=useState<PublicLife|null>(null);const [previous,setPrevious]=useState<Stats|undefined>();const [phase,setPhase]=useState('ready');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function start(){setBusy(true);setError('');try{const response=await fetch('/api/demo',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({role})});const data=await response.json();if(!response.ok)throw new Error(data.error);setLife(data);setPrevious(undefined);}catch(e){setError(e instanceof Error?e.message:'THE LIFE COULD NOT BEGIN.')}finally{setBusy(false)}}
 async function step(){if(!life||busy)return;setBusy(true);setPhase('thinking');setError('');try{const response=await fetch(`/api/demo/${life.id}/step`,{method:'POST'});const data=await response.json();if(!response.ok)throw new Error(data.error);await pause(350);setPrevious(life.stats);setLife(data);setPhase('choice');await pause(650);setPhase('consequence');await pause(800);setPhase('ready');}catch(e){setError(e instanceof Error?e.message:'THE DECISION DID NOT ARRIVE.');setPhase('ready')}finally{setBusy(false)}}
 return <><div className="page-head"><div className="shell"><span className="eyebrow">FIELD NOTE / THE PARTICIPANT</span><h1 className="display page-title">Begin a <em>brief eternity.</em></h1><p>Choose a starting condition. The server chooses the games and the seed. The baseline agent makes legal decisions; you watch what they cost.</p></div></div><div className="shell content">{error&&<p className="notice" role="alert">{error}</p>}{life?<LifeView life={life} previous={previous} phase={phase} onStep={step} busy={busy}/>:<><span className="eyebrow">01 / CHOOSE A ROLE</span><div className="role-grid">{(Object.keys(ROLES) as Role[]).map(r=><button type="button" className={`role-card ${role===r?'selected':''}`} key={r} onClick={()=>setRole(r)} aria-pressed={role===r} style={{background:role===r?'var(--surface2)':undefined,color:'var(--text)',textAlign:'left',cursor:'pointer'}}><Sprite role={r}/><h3>{r==='family'?'Family Person':r[0].toUpperCase()+r.slice(1)}</h3><p>{ROLES[r].description}</p><div className="tiny">{Object.entries(ROLES[r].stats).map(([key,value])=><div key={key}>{key.toUpperCase()} {value}</div>)}</div></button>)}</div><div style={{marginTop:30}}><button className="button" onClick={start} disabled={busy}>{busy?'A LIFE IS BEING WRITTEN.':'BEGIN AS '+role.toUpperCase()} <span>↗</span></button></div></>}</div></>}
function pause(ms:number){return new Promise(resolve=>setTimeout(resolve,ms))}
export default function Play(){return <Suspense fallback={<div className="shell content"><p className="thought">The first chapter is opening.</p></div>}><PlayContent/></Suspense>}
